version: '3.9'

services:
  unimestre:
    container_name: unimestre
    image: rovela/8.3.3-fpm-nginx
    restart: unless-stopped
    volumes:
      - ./image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./image-files/etc/nginx/http.d/default.conf:/etc/nginx/http.d/default.conf
      - ./image-files/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./image-files/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./image-files/usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./:/var/www/html
    external_links:
      - mysql_57
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "82:80"
    working_dir: /var/www/html
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512M

networks:
  default:
    external: true
    name: uni_network
