<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-5"><b>ÁREA DE CLIENTES</b></h1>

    <p>
        Escolha entre uma das opções habilitadas para o seu acesso.
    </p>
</div>

<div class="row ">

    <div class="col-sm-4 col-md-4 col-lg-2 text-center mx-auto mt-lg-5">
        <img src="/img/amais_chamado_on.png" alt="">
    </div>

    <div class="col-sm-4 col-md-4 col-lg-2 text-center mx-auto mt-lg-5">
        <img src="/img/amais_conteudo.png" alt="">
    </div>

    <div class="col-sm-4 col-md-4 col-lg-2 text-center mx-auto mt-lg-5">
        <img src="/img/amais_download_on.png" alt="">
    </div>

    <div class="col-sm-4 col-md-4 col-lg-2 text-center mx-auto mt-lg-5">
        <img src="/img/amais_corporativa.png" alt="">
    </div>

    <div class="col-sm-4 col-md-4 col-lg-2 text-center mx-auto mt-lg-5">
        <img src="/img/amais_usuario.png" alt="">
    </div>
</div>
