<?= $this->doctype() ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Amais Educação - Área de Clientes')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/faviconV2.png'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('fontawesome/css/all.min.css'))
?>
        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar mb-4" role="navigation">
            <div class="container">
                <a class="navbar-brand" href="<?= $this->url('rota-home') ?>">
                    <img src="<?= $this->basePath('img/logo-nova-amais-horizontal.svg') ?>"
                         alt="Amais Educação"
                         width="150"
                    /></a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mt-2">
                            <span class="navbar-text me-3">
                                Bruno Aurélio Rovela
                            </span>
                        </li>
                        <li class="nav-item">
                            <a  class="nav-link active"
                                aria-current="page"
                                href="<?= $this->url('rota-home') ?>"
                            ><i class="fa-solid fa-door-open"></i></a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>

            <hr class="mt-lg-5">

            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="https://amaiseducacao.com.br/" target="_blank">Amais Educação</a> Conectamos você à nova era da educação.
                </p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js')) ?>
    </body>
</html>
